### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by cetfu** [redstonetorchrockets/Bedrock-Rocket-resources#1]
Is there a new version of UIEngine.js? If yes, where do I download it?
I opened a thread because I couldn't find anything on the internet. I am sad.

**Comment by konrad2002** [comment]
Hi @honeybadger4768,
I'm sorry for the late reply. We stopped developing this pack in may 2020, so there won't be newer versions of our addons. But I can heartily recommend you to visit [bedrock.dev](https://bedrock.dev/) for all needed information about addon creation. Mojangs default pack can be found [here](https://bedrock.dev/packs).

**Comment by cetfu** [comment]
Thank you for reply. 😊
